// ==============================================================================
// SynapseLab — Application Constants
// ==============================================================================

export const ROLES = {
  RESEARCHER: 'RESEARCHER',
  PARTICIPANT: 'PARTICIPANT',
  ADMIN: 'ADMIN',
} as const;

export type UserRole = (typeof ROLES)[keyof typeof ROLES];

export const EXPERIMENT_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  PAUSED: 'PAUSED',
  CLOSED: 'CLOSED',
  ARCHIVED: 'ARCHIVED',
} as const;

export const EXPERIMENT_VISIBILITY = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
} as const;

export const ATTEMPT_POLICY = {
  ALLOW_ONE_ATTEMPT: 'ALLOW_ONE_ATTEMPT',
  ALLOW_MULTIPLE_ATTEMPTS: 'ALLOW_MULTIPLE_ATTEMPTS',
} as const;

export const SESSION_STATUS = {
  STARTED: 'STARTED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  ABANDONED: 'ABANDONED',
  EXCLUDED: 'EXCLUDED',
} as const;

export const QUALITY_FLAG_STATUS = {
  OPEN: 'OPEN',
  REVIEWED: 'REVIEWED',
  DISMISSED: 'DISMISSED',
  CONFIRMED: 'CONFIRMED',
} as const;

export const EXPORT_FORMAT = {
  CSV: 'CSV',
  XLSX: 'XLSX',
  JSON: 'JSON',
} as const;

export const EXPORT_STATUS = {
  QUEUED: 'QUEUED',
  PROCESSING: 'PROCESSING',
  READY: 'READY',
  FAILED: 'FAILED',
  EXPIRED: 'EXPIRED',
} as const;

export const RATING_REASONS = {
  EXPERIMENT_COMPLETION: 'EXPERIMENT_COMPLETION',
  SKIPPED_REQUIRED_QUESTIONS: 'SKIPPED_REQUIRED_QUESTIONS',
  INVALID_RESPONSE: 'INVALID_RESPONSE',
  EXTREMELY_FAST_RESPONSE: 'EXTREMELY_FAST_RESPONSE',
  REPEATED_IDENTICAL_RESPONSES: 'REPEATED_IDENTICAL_RESPONSES',
  FAILED_ATTENTION_CHECK: 'FAILED_ATTENTION_CHECK',
  RESEARCHER_QUALITY_FLAG: 'RESEARCHER_QUALITY_FLAG',
  ADMIN_ADJUSTMENT: 'ADMIN_ADJUSTMENT',
} as const;

export const RATING_SOURCES = {
  SYSTEM: 'SYSTEM',
  RESEARCHER: 'RESEARCHER',
  ADMIN: 'ADMIN',
} as const;

export const QUALITY_SIGNAL_TYPES = {
  EXTREMELY_FAST_RESPONSE: 'EXTREMELY_FAST_RESPONSE',
  REPEATED_IDENTICAL_RESPONSES: 'REPEATED_IDENTICAL_RESPONSES',
  FAILED_ATTENTION_CHECK: 'FAILED_ATTENTION_CHECK',
  INCONSISTENT_TIMING: 'INCONSISTENT_TIMING',
  IMPOSSIBLE_SEQUENCE: 'IMPOSSIBLE_SEQUENCE',
} as const;

export const AUDIT_ACTIONS = {
  // Auth
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_TOKEN_REFRESH: 'USER_TOKEN_REFRESH',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',

  // Experiments
  EXPERIMENT_CREATED: 'EXPERIMENT_CREATED',
  EXPERIMENT_UPDATED: 'EXPERIMENT_UPDATED',
  EXPERIMENT_PUBLISHED: 'EXPERIMENT_PUBLISHED',
  EXPERIMENT_PAUSED: 'EXPERIMENT_PAUSED',
  EXPERIMENT_CLOSED: 'EXPERIMENT_CLOSED',
  EXPERIMENT_ARCHIVED: 'EXPERIMENT_ARCHIVED',
  EXPERIMENT_VERSION_CREATED: 'EXPERIMENT_VERSION_CREATED',

  // Sessions
  SESSION_STARTED: 'SESSION_STARTED',
  SESSION_COMPLETED: 'SESSION_COMPLETED',
  SESSION_ABANDONED: 'SESSION_ABANDONED',
  EVENTS_INGESTED: 'EVENTS_INGESTED',

  // Quality
  QUALITY_FLAG_CREATED: 'QUALITY_FLAG_CREATED',
  QUALITY_FLAG_REVIEWED: 'QUALITY_FLAG_REVIEWED',
  RATING_EVENT_CREATED: 'RATING_EVENT_CREATED',
  DATA_EXCLUDED: 'DATA_EXCLUDED',

  // Consent
  CONSENT_GIVEN: 'CONSENT_GIVEN',
  CONSENT_WITHDRAWN: 'CONSENT_WITHDRAWN',

  // Export
  EXPORT_REQUESTED: 'EXPORT_REQUESTED',
  EXPORT_COMPLETED: 'EXPORT_COMPLETED',
  EXPORT_FAILED: 'EXPORT_FAILED',

  // Admin
  PERMISSION_CHANGED: 'PERMISSION_CHANGED',
  ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',
  ACCOUNT_REACTIVATED: 'ACCOUNT_REACTIVATED',
} as const;

// Pagination defaults
export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
} as const;

// Participant quality rating (Elo-like scale; new participants start at DEFAULT).
export const RATING = {
  MIN: 0,
  MAX: 3000,
  DEFAULT: 1200,
  /** Largest penalty a researcher may apply when confirming a quality flag. */
  MAX_RESEARCHER_PENALTY: 50,
} as const;

// Reward bounds
export const REWARD = {
  MIN: 0,
  MAX: 20,
} as const;

// Uploaded stimulus files
export const ASSET_LIMITS = {
  IMAGE_MAX_BYTES: 10 * 1024 * 1024,
  AUDIO_MAX_BYTES: 25 * 1024 * 1024,
} as const;
